---
title: "地理空間データの基本"
home: false
output:
  html_document:
    keep_md: true
---

## 地理空間データとは

我々が暮らす世界には、多くの地理空間データが存在しています。「地理空間データ」の定義は難しいですが、まずは空間上の特定の地点や領域とそれに紐付く情報と考えてみましょう。例えば次のものは地理空間データの一つです。

ここでは地物や事象の「状態」を表すための情報を地理空間情報として扱います。地理空間情報は文字通り、地球上での**位置**や**形状**を記録するデータです。

身の回りにあるものは位置情報を持っています。


- それに付随する属性情報

### 地物とは何か

### データ構造

地理空間情報をどのようにコンピュータ上に表現するかというデータ構造には、さまざまな表現形態があります。それは地理空間情報がどのように記録されるか・取り扱うかによって大きく2種類に分けて考えることができます。

- **ベクタ**
- **ラスタ**

これらについて、次に詳しく説明します。

### ベクタ

ベクトル、ベクターと呼ばれるデータ形式は、一般に、点、線、面で表現されるものです。これらは現実の世界に目に見えないもの (行政区域など実際には存在しないもの) も含めてありますが、いずれも存在する地物です。

- 座標と属性情報をもち、地図上で表現できる
- ポリゴンは、(x,y)の座標値を結んだ閉じた線分として格納される

ベクトルデータに格納される属性情報は、一般的にテーブル形式で格納され、図形情報と関連づけられています。

### ラスタ

- 明確な形状として区切ることができない、連続的に変化する状態や広がりを持つもの
- 行と列の格子状(グリッド状)に並んだセル(ピクセル)で構成されるデータ
- 各セルに情報を表す量が含まれる


### 次元

全てのジオメトリ (geometry) はポイントの集合によって形成されます。ある一カ所を示す点は一つのポイントです。2点を結ぶラインは始点と終点の2つのポイントをもちます。多角形のジオメトリであるポリゴンでは、いくつかの頂点が存在します。これらはジオメトリを構成する原子のようなものです。

ポイントは2次元から4次元の座標です。あるジオメトリにおいて、全てのポイントは同じ次元を有していなければいけません。1次元のポイントというのは存在しなく、どのポイントも`X`、`Y`の2点の座標値を含みます。

2以上の次元として、`Z`、`M`が使われることがあります。`Z`座標は高度や標高を示します。また`M`座標は他の次元と紐付く値尺 (measure) です。測定の時間や計測誤差などの記録のためのもので頻繁に使われるものではありません。

ポイントは、他のジオメトリを構成する要素となります。

### 座標参照系 (CRS)

地球上の地物の位置を示すために、座標に加えて座標参照系 (Coordinate Reference System: CRS) の定義が必要になります。これは二次元の座標を地球上に投影するための位置関係と紐づけるために使われます。言い換えると、座標参照系が判明している時にのみ座標を地球の表面に置くことができます。

「座標」にはこれまでの例でみてきたXY座標を使ったものに加えて、緯度経度で表現されるものもあります。また地図投影法により定義された値を座標として使うこともあります。

座標参照系は地理座標系と投影座標系に大別されます。
